// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATCsxAUt6f-SPZCyNATRy4JFdqADao54',
    appId: '1:335263260944:web:77f613c24bc8c33a640595',
    messagingSenderId: '335263260944',
    projectId: 'hatgeback',
    authDomain: 'hatgeback.firebaseapp.com',
    storageBucket: 'hatgeback.appspot.com',
    measurementId: 'G-4358KG8XGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrdLj6UT-uy-yfQWIHnxGdC5cVe5hKOmw',
    appId: '1:335263260944:android:a62ded53d7bfbae0640595',
    messagingSenderId: '335263260944',
    projectId: 'hatgeback',
    storageBucket: 'hatgeback.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFl3pW2exNSJ-hIXDHe38Yu-gVM7pNdv8',
    appId: '1:335263260944:ios:0e81f1e38feacfaf640595',
    messagingSenderId: '335263260944',
    projectId: 'hatgeback',
    storageBucket: 'hatgeback.appspot.com',
    iosBundleId: 'com.example.hatgeback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFl3pW2exNSJ-hIXDHe38Yu-gVM7pNdv8',
    appId: '1:335263260944:ios:1e794bd7954b5ba9640595',
    messagingSenderId: '335263260944',
    projectId: 'hatgeback',
    storageBucket: 'hatgeback.appspot.com',
    iosBundleId: 'com.example.hatgeback.RunnerTests',
  );
}
